feat: upgrade for @kaiu/serializer v1.0.1
kaiu-io/ng-serializer pull request #1
Opened 2017-08-11 08:21 UTC by Supamiu

This PR contains a lot of things:

- `forChild` addition.
- Travis fixes & codecov fixes.
- @kaiu/serializer v1.0.1 compatibility.
- Renaming.

2017-08-11 12:22 UTC, noemi-salaun requested changes

2017-08-11 12:22 UTC, noemi-salaun commented on src/ng-serializer.factory.ts
> +    //The concat called here is used to flatten the array., allowing multi:true in provider.
There is a comma typo

2017-08-11 12:22 UTC, noemi-salaun commented on src/ng-serializer.service.ts
> +    constructor(public readonly registry: Registry) {
No need to make the registry public readonly in this constructor, the Parent constructor will take care of it

2017-08-11 12:27 UTC, Supamiu commented on src/ng-serializer.service.ts
> +    constructor(public readonly registry: Registry) {
This has been done because else aot can't resolve all parameters for this service.

2017-08-28 10:17 UTC, noemi-salaun requested changes

2017-08-28 10:17 UTC, noemi-salaun commented on src/ng-serializer.service.ts
> +    constructor(public readonly registry: Registry) {
You can inject the registry and then pass it to the parent constructor

```ts
constructor(registry: Registry) {
    super(registry);
}
```

2017-08-28 11:20 UTC, noemi-salaun approved these changes

2017-08-28 11:22 UTC, merged